In [ ]:
import numpy as np
a = np.array([1,2,3],dtype=float)
b = np.array([10,20,30],dtype=float)
print(a+b)
print(a*b)
print(a/b)
print(a**2)
print(np.sqrt(a))
print(np.round(np.sqrt(b),2))

[11. 22. 33.]
[10. 40. 90.]
[0.1 0.1 0.1]
[1. 4. 9.]
[1.         1.41421356 1.73205081]
[3.16 4.47 5.48]


In [14]:
x = np.linspace(0,2*np.pi,5)
print(np.round(np.sin(x),3))
y = np.array([-1,0,1,np.e,np.e**2])
print(np.abs(y))
print(np.round(np.log(y[y>0]),3))
a = np.array([1,8,3]);b = np.array([4,5,2])
print(np.maximum(a,b))
print(np.max(a))

[ 0.  1.  0. -1. -0.]
[1.         0.         1.         2.71828183 7.3890561 ]
[0. 1. 2.]
[4 8 3]
8


In [18]:
M = np.arange(12).reshape(3,4)
print(M.sum())
print(M.sum(axis=0))
print(M.mean(axis=1))
print(M.mean(axis=1,keepdims=True))
print(M.std(axis=0).round(2))

66
[12 15 18 21]
[1.5 5.5 9.5]
[[1.5]
 [5.5]
 [9.5]]
[3.27 3.27 3.27 3.27]


In [19]:
arr = np.arange(6).reshape(2,3)
print(arr + 10)
row = np.array([100,200,300])
print(arr + row)

[[10 11 12]
 [13 14 15]]
[[100 201 302]
 [103 204 305]]


In [21]:
x = np.array([1,2,3])
y = np.array([10,20,30,40])
R = x[:,np.newaxis] + y
print(R)
print(R.shape)
i = np.arange(1,10)
print((i[:,None]*i))

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]
(3, 4)
[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


In [23]:
arr = np.array([3,-1,7,-5,0,9,2])
print(np.where(arr < 0,0,arr))
print(np.where(arr > 0))
print(arr[np.where(arr > 0)[0]])
conds = [arr < 0,arr == 0,arr > 0 ]
choices = ['neg','zero','pos']
print(np.select(conds,choices,default='unknown'))

[3 0 7 0 0 9 2]
(array([0, 2, 5, 6]),)
[3 7 9 2]
['pos' 'neg' 'pos' 'neg' 'zero' 'pos' 'pos']


In [30]:
arr = np.array([3,1,4,1,5,9,2,6])
#print(np.sort(arr))
#print(arr.sort())
idx = np.argsort(arr)
print(idx)
top3_idx = idx[-3:][::-1]
print(top3_idx)
print(arr[top3_idx])
M = np.array([[3,1,2],[6,4,5]])
print(np.sort(M,axis=1))

[1 3 6 0 2 4 7 5]
[5 7 4]
[9 6 5]
[[1 2 3]
 [4 5 6]]


In [37]:
A = np.array([[1,2],[3,4]],dtype=float)
b = np.array([5,11])
print(A@A)
print(A*A)
x = np.linalg.solve(A,b)
print(x)
print(np.linalg.det(A))
print(np.linalg.inv(A).round(3))
print(np.linalg.eigvals(A))
v = np.array([3,4])
print(np.linalg.norm(v))

[[ 7. 10.]
 [15. 22.]]
[[ 1.  4.]
 [ 9. 16.]]
[1. 2.]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
[-0.37228132  5.37228132]
5.0


In [42]:
P = np.array([[0,0],[1,2],[3,1],[4,4],[2,5]],dtype=float)
diff = P[:,None,:]-P[None,:,:]
print(P[:,None,:])
print(P[None,:,:])
print(diff)
D = np.sqrt((diff**2).sum(axis=-1))
print(D.round(2))
print(np.allclose(np.diag(D),0))
print(np.allclose(D,D.T))

[[[0. 0.]]

 [[1. 2.]]

 [[3. 1.]]

 [[4. 4.]]

 [[2. 5.]]]
[[[0. 0.]
  [1. 2.]
  [3. 1.]
  [4. 4.]
  [2. 5.]]]
[[[ 0.  0.]
  [-1. -2.]
  [-3. -1.]
  [-4. -4.]
  [-2. -5.]]

 [[ 1.  2.]
  [ 0.  0.]
  [-2.  1.]
  [-3. -2.]
  [-1. -3.]]

 [[ 3.  1.]
  [ 2. -1.]
  [ 0.  0.]
  [-1. -3.]
  [ 1. -4.]]

 [[ 4.  4.]
  [ 3.  2.]
  [ 1.  3.]
  [ 0.  0.]
  [ 2. -1.]]

 [[ 2.  5.]
  [ 1.  3.]
  [-1.  4.]
  [-2.  1.]
  [ 0.  0.]]]
[[0.   2.24 3.16 5.66 5.39]
 [2.24 0.   2.24 3.61 3.16]
 [3.16 2.24 0.   3.16 4.12]
 [5.66 3.61 3.16 0.   2.24]
 [5.39 3.16 4.12 2.24 0.  ]]
True
True
