In [ ]:
import numpy as np
print(f"当前Numpy版本:{np.__version__}")
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print("数组内容:\n",arr)

当前Numpy版本:2.4.6
数组内容:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [1]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [2]:
import numpy as np
zeros_arr = np.zeros((3,4))
print(zeros_arr)
print("形状:",zeros_arr.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
形状: (3, 4)


In [4]:
import numpy as np
ones_arr = np.ones((2,2),dtype=np.float32)
print(ones_arr)
print("数据类型:",ones_arr.dtype)

[[1. 1.]
 [1. 1.]]
数据类型: float32


In [5]:
import numpy as np
even_arr = np.arange(0,20,2)
print(even_arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [6]:
import numpy as np
lin_arr = np.linspace(0,1,6)
print(lin_arr)

[0.  0.2 0.4 0.6 0.8 1. ]


In [7]:
import numpy as np
arr_3d = np.zeros((2,3,4))
print("维度数ndim:",arr_3d.ndim)
print("形状shape:",arr_3d.shape)
print("元素总数size:",arr_3d.size)

维度数ndim: 3
形状shape: (2, 3, 4)
元素总数size: 24


In [8]:
import numpy as np
identity_arr = np.eye(4)
print(identity_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
import numpy as np
mixed_arr = np.array([1,2,3.14])
print(mixed_arr)
print("数据类型:",mixed_arr.dtype)

[1.   2.   3.14]
数据类型: float64


In [12]:
import numpy as np
arr = np.zeros(1000,dtype=np.float64)
total_bytes = arr.size * arr.itemsize
print(f"元素个数:{arr.size}")
print(f"单元素字节:{arr.itemsize}")
print(f"总占用内存:{total_bytes}字节")
print(f"约{total_bytes / 1024:.2f}KB")

元素个数:1000
单元素字节:8
总占用内存:8000字节
约7.81KB


In [15]:
point = (1,2,3,4)
color = ('红','绿','蓝')
mixed = (1,'hello',3.14,True)
single = (42,)
not_tuple = (42)
print(type(single))
print(type(not_tuple))
empty = ()
print(type(empty))

<class 'tuple'>
<class 'int'>
<class 'tuple'>


In [19]:
point = (3,5)
print(point[0])
print(point[1:])
print(len(point))
print(3 in point)
print(point.count(3))
print(point.index(5))

3
(5,)
2
True
1
1


In [24]:
point = (3,5)
x,y = point
print(f"x={x},y={y}")
name,age,city = ('小明',20,'苏州')
print(name,age,city)
a,b = 1,2
a,b = b,a
print(a,b)
first,*rest = (1,2,3,4,5)
print(first)
print(rest)

x=3,y=5
小明 20 苏州
2 1
1
[2, 3, 4, 5]


In [25]:
first,second,*rest = (1,2,3,4,5)
print(first)
print(second)
print(rest)

1
2
[3, 4, 5]


In [ ]:
*init,last = (1,2,3,4,5)
print(init)
print(last)

[1, 2, 3, 4]
5


In [27]:
first,*middle,last = (1,2,3,4,5)
print(first)
print(middle)
print(last)

1
[2, 3, 4]
5


In [28]:
x,_,z = (1,2,3)
print(x,z)

1 3


In [29]:
student = ('小明',(85,92,78))
name,(chinese,math,english) = student
print(f"{name}:语文{chinese},数学{math},英语{english}")

小明:语文85,数学92,英语78


In [3]:
import sys
my_list = [1,2,3,4,5]
my_tuple = (1,2,3,4,5)
print(f"列表占用内存:{sys.getsizeof(my_list)}字节")
print(f"元组占用内存:{sys.getsizeof(my_tuple)}字节")
locations = {
    (0,0):"原点",
    (1,2):"A点",
    (3,4):"B点",
}
print(locations[(1,2)])

列表占用内存:104字节
元组占用内存:80字节
A点


In [7]:
def get_min_max(numbers):
    return min(numbers),max(numbers)
result = get_min_max([3,1,4,1,5,9])
print(result)
print(type(result))
minimum,maximum = get_min_max([3,1,4,1,5,9])
print(f"最小值:{minimum},最大值:{maximum}")
point = (10,20)
color = (255,128,0)
date = (2026,9,10)
person = {"name":"小明","age":20,"city":"苏州"}
for key,value in person.items():
    print(f"{key}:{value}")
students = [
    ("小明",85,92),
    ("小红",90,88),
    ("小刚",72,65),
]
students.append(("小丽",95,97))

(1, 9)
<class 'tuple'>
最小值:1,最大值:9
name:小明
age:20
city:苏州


In [10]:
my_list = [1,2,3,4,5]
my_tuple = tuple(my_list)
print(my_tuple)
my_tuple = (1,2,3,4,5)
my_list = list(my_tuple)
print(my_list)
point = (3,5)
temp_list = list(point)
temp_list[0] = 10
point = tuple(temp_list)
print(point)

(1, 2, 3, 4, 5)
[1, 2, 3, 4, 5]
(10, 5)


In [ ]:
point_a = (3,4)
point_b = (7,1)
print(f"点A:{point_a}")
print(f"点B:{point_b}")
print(f"点A的x坐标:{point_a[0]}")
print(f"点B的y坐标:{point_b[1]}")
combined = point_a + point_b
print(f"合并{combined}")
repeated = point_a * 3
print(f"重复:{repeated}")
student = ("小明",20,"苏州","工程师")
name,age,city,job = student
print(f"\n{name},{age}岁,{city},{job}")
first,*middle,last = (10,20,30,40,50,60)
print(f"首{first},中间{middle},尾{last}")
record = ("订单001",("iPhone 15",5999),2)
order_id,(product,price),quantity = record
total = price * quantity
print(f"\n订单{order_id}:{product}x{quantity} = ￥{total}")

点A:(3, 4)
点B:(7, 1)
点A的x坐标:3
点B的y坐标:1
合并(3, 4, 7, 1)
重复:(3, 4, 3, 4, 3, 4)

小明,20岁,苏州,工程师
首10,中间[20, 30, 40, 50],尾60

订单订单001:iPhone 15x2 = ￥11998


In [ ]:
import math
def distance(p1,p2):
    x1,y1 = p1
    x2,y2 = p2
    return math.sqrt((x2-x1)**2 + (y2-y1)**2)
point_a = (0,0)
point_b = (3,4)
d = distance(point_a,point_b)
print(f"\n{point_a}到{point_b}的距离{d}")
point_c = (1,1)
point_d = (4,5)
d2 = distance(point_c,point_d)
print(f"{point_c}到{point_d}的距离{d2}")



(0, 0)到(3, 4)的距离5.0
(1, 1)到(4, 5)的距离5.0


In [22]:
def analyze_numbers(numbers):
    return (
        min(numbers),
        max(numbers),
        sum(numbers),
        sum(numbers) / len(numbers),
        len(numbers)
    )
scores = [78, 92, 65, 88, 45, 91, 73, 56, 82, 97]
result = analyze_numbers(scores)
print(f"\n统计结果(元组):{result}")
minimum,maximum,total,average,count = analyze_numbers(scores)
print(f"最小值:{minimum}")
print(f"最大值:{maximum}")
print(f"总和:{total}")
print(f"平均值:{average:.1f}")
print(f"个数:{count}")


统计结果(元组):(45, 97, 767, 76.7, 10)
最小值:45
最大值:97
总和:767
平均值:76.7
个数:10


In [23]:
city_map = {
    (0, 0): "🏠 家",
    (2, 3): "🏫 学校",
    (5, 1): "🛒 超市",
    (3, 7): "🏥 医院",
    (8, 4): "🌳 公园",
}
print("\n=== 简易地图 ===")
for coord,place in city_map.items():
    print(f"   坐标{coord}:{place}")


=== 简易地图 ===
   坐标(0, 0):🏠 家
   坐标(2, 3):🏫 学校
   坐标(5, 1):🛒 超市
   坐标(3, 7):🏥 医院
   坐标(8, 4):🌳 公园
