In [8]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
print(A)
print(A.shape)
print(A.ndim)
print(A.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int64


In [9]:
import numpy as np
Z = np.zeros((3,3))
print(Z)
O = np.ones((2,4))
print(O)
I = np.eye(3)
print(I)
J = np.random.rand(2,2)
print(J)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.55452391 0.46466773]
 [0.02860045 0.190739  ]]


In [10]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
print(A)
print(A[0,2])
row_0 = A[0]
col1 = A[:,1]
print(row_0)
print(col1)
sub = A[:2,:2]
print(sub)
sub_copy = A[:2,:2].copy()
print(sub_copy)

[[1 2 3]
 [4 5 6]]
3
[1 2 3]
[2 5]
[[1 2]
 [4 5]]
[[1 2]
 [4 5]]


In [11]:
import numpy as np
B = np.array([[1,2,3,4,5,6]])
M = B.reshape(2,3)
print(M)
V = M.reshape(-1)
print(V)
v1 = M.flatten()
v2 = M.ravel()
print(v1)
print(v2)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [12]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[10,20,30],[40,50,60]])
C= A + B
D = 3 * A
print(A)
print(B)
print(C)
print(D)

[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50 60]]
[[11 22 33]
 [44 55 66]]
[[ 3  6  9]
 [12 15 18]]


In [13]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A * A)
print(A @ B)
print(A.dot(B))
X = np.array([1,2])
Y = X @ A
Z = A @ X
print(X)
print(Y)
print(Z)


[[ 1  4]
 [ 9 16]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[1 2]
[ 7 10]
[ 5 11]


In [14]:
import numpy as np
A = np.array([[1,2],[3,4]])
X = np.array([1,2])
Y = X @ A
Z = A @ X
print(X)
print(Y)
print(Z)

[1 2]
[ 7 10]
[ 5 11]


In [15]:
import numpy as np
matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])
print("--- 1. 基本切片操作 ---")
sub_matrix1 = matrix[0:2,1:4]
print("子矩阵1 (matrix[0:2, 1:4]):\n", sub_matrix1)
sub_matrix2 = matrix[:,1:]
print("\n子矩阵2 (matrix[:, 1:]):\n", sub_matrix2)
sub_matrix3 = matrix[::,::2]
print("\n子矩阵3 (matrix[::, ::2]):\n", sub_matrix3)
sub_matrix4 = matrix[-2:,:]
print("\n子矩阵4 (matrix[-2:, :]):\n", sub_matrix4)


--- 1. 基本切片操作 ---
子矩阵1 (matrix[0:2, 1:4]):
 [[2 3 4]
 [7 8 9]]

子矩阵2 (matrix[:, 1:]):
 [[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]]

子矩阵3 (matrix[::, ::2]):
 [[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]]

子矩阵4 (matrix[-2:, :]):
 [[11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
import numpy as np
matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])
print(matrix)
print("\n--- 2. 高级索引操作 (使用 np.ix_) ---")
rows = [0,2]
cols = [1,3]
sub_matrix5 = matrix[np.ix_(rows,cols)]
print("子矩阵5 (matrix[np.ix_([0, 2], [1, 3])]):\n", sub_matrix5)
print("\n--- 3. 混合索引操作 ---")
sub_matrix6 = matrix[[0,2],:][:,1:4]
print("子矩阵6 (matrix[[0, 2], :][:, 1:4]):\n", sub_matrix6)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

--- 2. 高级索引操作 (使用 np.ix_) ---
子矩阵5 (matrix[np.ix_([0, 2], [1, 3])]):
 [[ 2  4]
 [12 14]]

--- 3. 混合索引操作 ---
子矩阵6 (matrix[[0, 2], :][:, 1:4]):
 [[ 2  3  4]
 [12 13 14]]


In [18]:
import numpy as np
def create_zero_matrix(m,n):
    return np.zeros((m,n))
def create_ones_matrix(m,n):
    return np.ones((m,n))
def create_identity_matrix(n):
    return np.eye(n)
def create_diagonal_matrix(diagonal_elements):
    return np.diag(diagonal_elements)
def create_random_matrix(m,n):
    return np.random.rand(m,n)
def reshape_matrix(matrix,new_shape):
    return np.reshape(matrix,new_shape)
def transpose_matrix(matrix):
    return matrix.T
def matrix_addition(matrix_a,matrix_b):
    return matrix_a + matrix_b
def scalar_multiplication(matrix,scalar):
    return scalar * matrix

if __name__ == "__main__":
    print("--- 1. 特殊矩阵生成 ---")
    print("2x3 全零矩阵:\n", create_zero_matrix(2, 3))
    print("\n3x2 全一矩阵:\n", create_ones_matrix(3, 2))
    print("\n4 阶单位矩阵:\n", create_identity_matrix(4))
    print("\n对角矩阵 (对角线元素为 [1, 2, 3]):\n", create_diagonal_matrix([1, 2, 3]))
    print("\n2x4 随机矩阵:\n", create_random_matrix(2, 4))
    print("\n--- 2. 矩阵变换与操作 ---")
    A = np.array([[1, 2, 3], [4, 5, 6]])
    print("\n原始矩阵 A:\n", A)
    print("\n重塑 A 为 3x2 矩阵:\n", reshape_matrix(A, (3, 2)))
    print("\n矩阵 A 的转置:\n", transpose_matrix(A))
    B = np.array([[7, 8, 9], [10, 11, 12]])
    print("\n矩阵 B:\n", B)
    print("\nA + B:\n", matrix_addition(A, B))
    print("\n2 * A:\n", scalar_multiplication(A, 2))

--- 1. 特殊矩阵生成 ---
2x3 全零矩阵:
 [[0. 0. 0.]
 [0. 0. 0.]]

3x2 全一矩阵:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

4 阶单位矩阵:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

对角矩阵 (对角线元素为 [1, 2, 3]):
 [[1 0 0]
 [0 2 0]
 [0 0 3]]

2x4 随机矩阵:
 [[0.33434653 0.87684102 0.46070295 0.43788633]
 [0.79446736 0.25902067 0.55547225 0.63539376]]

--- 2. 矩阵变换与操作 ---

原始矩阵 A:
 [[1 2 3]
 [4 5 6]]

重塑 A 为 3x2 矩阵:
 [[1 2]
 [3 4]
 [5 6]]

矩阵 A 的转置:
 [[1 4]
 [2 5]
 [3 6]]

矩阵 B:
 [[ 7  8  9]
 [10 11 12]]

A + B:
 [[ 8 10 12]
 [14 16 18]]

2 * A:
 [[ 2  4  6]
 [ 8 10 12]]


In [19]:
import numpy as np
def create_zero_matrix(m,n):
    return np.zeros((m,n))
def create_ones_matrix(m,n):
    return np.ones((m,n))
def create_identity_matrix(n):
    return np.eye(n)
def create_diagonal_matrix(diagonal_elements):
    return np.diag(diagonal_elements)
def create_random_matrix(m,n):
    return np.random.rand(m,n)
def reshape_matrix(matrix,new_shape):
    return np.reshape(matrix,new_shape)
def transpose_matrix(matrix):
    return matrix.T
def matrix_addition(matrix_a,matrix_b):
    return matrix_a + matrix_b
def scalar_multiplication(matrix,scalar):
    return scalar * matrix

if __name__ == "__main__":
    print("--- 1. 特殊矩阵生成 ---")
    print("2x3 全零矩阵:\n", create_zero_matrix(2, 3))
    print("\n3x2 全一矩阵:\n", create_ones_matrix(3, 2))
    print("\n4 阶单位矩阵:\n", create_identity_matrix(4))
    print("\n对角矩阵 (对角线元素为 [1, 2, 3]):\n", create_diagonal_matrix([1, 2, 3]))
    print("\n2x4 随机矩阵:\n", create_random_matrix(2, 4))
    print("\n--- 2. 矩阵变换与操作 ---")
    A = np.array([[1, 2, 3], [4, 5, 6]])
    print("\n原始矩阵 A:\n", A)
    print("\n重塑 A 为 3x2 矩阵:\n", reshape_matrix(A, (3, 2)))
    print("\n矩阵 A 的转置:\n", transpose_matrix(A))
    B = np.array([[7, 8, 9], [10, 11, 12]])
    print("\n矩阵 B:\n", B)
    print("\nA + B:\n", matrix_addition(A, B))
    print("\n2 * A:\n", scalar_multiplication(A, 2))


--- 1. 特殊矩阵生成 ---
2x3 全零矩阵:
 [[0. 0. 0.]
 [0. 0. 0.]]

3x2 全一矩阵:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

4 阶单位矩阵:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

对角矩阵 (对角线元素为 [1, 2, 3]):
 [[1 0 0]
 [0 2 0]
 [0 0 3]]

2x4 随机矩阵:
 [[0.22048654 0.24320475 0.67830267 0.31360389]
 [0.61990538 0.60133199 0.12287211 0.13751179]]

--- 2. 矩阵变换与操作 ---

原始矩阵 A:
 [[1 2 3]
 [4 5 6]]

重塑 A 为 3x2 矩阵:
 [[1 2]
 [3 4]
 [5 6]]

矩阵 A 的转置:
 [[1 4]
 [2 5]
 [3 6]]

矩阵 B:
 [[ 7  8  9]
 [10 11 12]]

A + B:
 [[ 8 10 12]
 [14 16 18]]

2 * A:
 [[ 2  4  6]
 [ 8 10 12]]


In [20]:
import numpy as np
matrix_list = [np.random.rand(30,20)for _ in range(10)]
print(f"列表长度: {len(matrix_list)}")
print(f"第一个矩阵的形状: {matrix_list[0].shape}")

列表长度: 10
第一个矩阵的形状: (30, 20)


In [28]:
import numpy as np
A = np.array([[1,2],[3,4]])
print(np.linalg.det(A))
B = np.array([[1,2,3],[4,5,6],[7,8,10]])
print(int(np.linalg.det(B)))
R = np.random.rand(5,5)
print(np.linalg.det(R))


-2.0000000000000004
-2
0.024419024675882816


In [33]:
import random
print(random.random())
print(random.uniform(3,4))
print(random.randint(6,10))
print(random.randrange(2,100,3))

0.2026300031319468
3.9402498551189638
8
71


In [48]:
my_list = ['apple', 'banana', 'cherry', 'date']
print(random.choice(my_list))
print(random.sample(my_list,2))
random.shuffle(my_list)
print(my_list)

date
['cherry', 'banana']
['date', 'cherry', 'apple', 'banana']


In [60]:
print(random.gauss(0,1))

1.5964643520899118


In [67]:
import csv
with open('sales_data.csv',mode = 'r',encoding='UTF-8') as f:
    reader = csv.DictReader(f)
    data_list = list(reader)
print(data_list)

[{'Order_ID': 'ORD-1001', 'Date': '2023-10-01', 'Customer_ID': 'C-8832', 'Product': 'Wireless Mouse', 'Category': 'Electronics', 'Quantity': '2', 'Unit_Price': '25.50', 'Total_Amount': '51.00'}, {'Order_ID': 'ORD-1002', 'Date': '2023-10-01', 'Customer_ID': 'C-4421', 'Product': 'Office Chair', 'Category': 'Furniture', 'Quantity': '1', 'Unit_Price': '149.99', 'Total_Amount': '149.99'}, {'Order_ID': 'ORD-1003', 'Date': '2023-10-02', 'Customer_ID': 'C-8832', 'Product': 'USB-C Cable', 'Category': 'Electronics', 'Quantity': '5', 'Unit_Price': '9.99', 'Total_Amount': '49.95'}, {'Order_ID': 'ORD-1004', 'Date': '2023-10-02', 'Customer_ID': 'C-1290', 'Product': 'Notebook', 'Category': 'Stationery', 'Quantity': '10', 'Unit_Price': '3.50', 'Total_Amount': '35.00'}, {'Order_ID': 'ORD-1005', 'Date': '2023-10-03', 'Customer_ID': 'C-5562', 'Product': 'Coffee Maker', 'Category': 'Appliances', 'Quantity': '1', 'Unit_Price': '89.00', 'Total_Amount': '89.00'}, {'Order_ID': 'ORD-1006', 'Date': '2023-10-03'

In [71]:
import numpy as np
def create_matrix_list():
    matrix_list = []
    matrix_list.append(("零矩阵 (2x3)", np.zeros((2, 3))))
    matrix_list.append(("全一矩阵 (3x2)", np.ones((3, 2))))
    matrix_list.append(("单位矩阵 (3x3)", np.eye(3)))
    matrix_list.append(("对角矩阵 (基于[1,2,3])", np.diag([1, 2, 3])))
    matrix_list.append(("随机矩阵 (2x2, 均匀分布)", np.random.rand(2, 2)))
    A = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])
    matrix_list.append(("对称矩阵 A", A))
    theta = np.pi / 4  # 45度
    Q = np.array([[np.cos(theta), -np.sin(theta)], 
                    [np.sin(theta), np.cos(theta)]])
    matrix_list.append(("正交矩阵 Q (旋转45度)", Q))
    U = np.triu(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))
    matrix_list.append(("上三角矩阵 U", U))
    c = [1, 2, 3, 4] # 第一列
    r = [1, 5, 6, 7] # 第一行
    T = np.array([[c[i-j] if i>=j else r[j-i] for j in range(len(r))] for i in range(len(c))])
    matrix_list.append(("Toeplitz 矩阵 T (自定义)", T))
    x = np.array([1, 2, 3, 4])
    V = np.vander(x, N=4, increasing=True)
    matrix_list.append(("Vandermonde 矩阵 V (基于[1,2,3,4])", V))
    return matrix_list
if __name__ == "__main__":
    matrices = create_matrix_list()
    print("===== 矩阵列表示例 =====")
    for i, (name, matrix) in enumerate(matrices):
        print(f"\n--- 矩阵 {i+1}: {name} ---")
        print(matrix)

===== 矩阵列表示例 =====

--- 矩阵 1: 零矩阵 (2x3) ---
[[0. 0. 0.]
 [0. 0. 0.]]

--- 矩阵 2: 全一矩阵 (3x2) ---
[[1. 1.]
 [1. 1.]
 [1. 1.]]

--- 矩阵 3: 单位矩阵 (3x3) ---
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

--- 矩阵 4: 对角矩阵 (基于[1,2,3]) ---
[[1 0 0]
 [0 2 0]
 [0 0 3]]

--- 矩阵 5: 随机矩阵 (2x2, 均匀分布) ---
[[0.44082882 0.91708139]
 [0.32548061 0.4019975 ]]

--- 矩阵 6: 对称矩阵 A ---
[[1 2 3]
 [2 4 5]
 [3 5 6]]

--- 矩阵 7: 正交矩阵 Q (旋转45度) ---
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

--- 矩阵 8: 上三角矩阵 U ---
[[1 2 3]
 [0 5 6]
 [0 0 9]]

--- 矩阵 9: Toeplitz 矩阵 T (自定义) ---
[[1 5 6 7]
 [2 1 5 6]
 [3 2 1 5]
 [4 3 2 1]]

--- 矩阵 10: Vandermonde 矩阵 V (基于[1,2,3,4]) ---
[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]


In [ ]:
from datetime import datetime
from pathlib import Path
file_path = Path("diary.txt")
content = input("今天发生了什么?(输入内容):")
timestamp = datetime.now().strftime("%Y-%m-%D %H:%M:%S")
with open(file_path,'a',encoding='UTF-8') as f:
    f.write(f"[{timestamp}]{content}\n")
print("日记保存成功!")

In [4]:
with open('article.txt','w',encoding='UTF-8') as f:
    f.write('我今天买了一个苹果,苹果非常好吃。')
with open('article.txt','r',encoding='UTF-8') as f_in:
    text = f_in.read()
clean_text = text.replace('苹果','水果')
with open('article.txt','w',encoding='UTF-8') as f_out:
    f_out.write(clean_text)

In [1]:
with open('diary.txt','w',encoding='UTF-8') as f:
    f.write("""
    2025年10月24日 晴
    今天学习了Python文件操作。
    感觉非常有成就感!""")
with open('diary.txt','r',encoding='UTF-8') as f:
    print('原始日记')
    print(f.read())

原始日记

    2025年10月24日 晴
    今天学习了Python文件操作。
    感觉非常有成就感!


In [2]:
with open('diary.txt','w',encoding='UTF-8') as f:
    f.write("""
    2025年10月24日 晴
    今天学习了Python文件操作。
    感觉非常有成就感!""")
with open('diary.txt','r',encoding='UTF-8') as f:
    print('原始日记')
    print(f.read())
with open('diary.txt','r',encoding='UTF-8') as f:
    content = f.read()
new_content = content.replace('成就感','挫败感')
with open('diary.txt','w',encoding='UTF-8') as f:
    f.write(new_content)
with open('diary.txt','r',encoding='UTF-8') as f:  
    print('修改后的日记')
    print(f.read())

原始日记

    2025年10月24日 晴
    今天学习了Python文件操作。
    感觉非常有成就感!
修改后的日记

    2025年10月24日 晴
    今天学习了Python文件操作。
    感觉非常有挫败感!


In [3]:
log_data = """[08:00:01] INFO: Server started successfully.
[08:15:22] INFO: User 'admin' logged in.
[08:20:45] WARNING: High CPU usage detected (85%).
[08:22:10] ERROR: Database connection timeout!
[08:25:00] INFO: Backup process initiated.
[08:30:12] ERROR: Failed to write to disk /dev/sda1.
[09:00:00] INFO: Scheduled task completed."""
with open('sever.log','w',encoding='UTF-8') as f:
    f.write(log_data)
with open('sever.log','r',encoding='UTF-8') as f_in,\
     open('error_only.log','w',encoding='UTF-8') as f_out:
    error_count = 0
    for line in f_in:
        if 'ERROR' in line:
            f_out.write(line)
            error_count += 1
print(f"清洗完成,发现{error_count}条错误。")
with open('error_only.log','r',encoding='UTF-8') as f:
    print("错误日志内容")
    print(f.read())

清洗完成,发现2条错误。
错误日志内容
[08:22:10] ERROR: Database connection timeout!
[08:30:12] ERROR: Failed to write to disk /dev/sda1.

