In [1]:
import torch

# 3 张图: 3, 4, 5 节点. N_max = 5
B, N_max = 3, 5
sizes = [3, 4, 5]

mask = torch.zeros(B, N_max, dtype=torch.bool)
for i, n in enumerate(sizes):
    mask[i, :n] = True   # 前 n 个位置设为 True

print('Mask:')
print(mask.int())  # int() 让 0/1 更直观
print(f'每张图的真实节点数: {mask.sum(dim=1).tolist()}')

Mask:
tensor([[1, 1, 1, 0, 0],
        [1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1]], dtype=torch.int32)
每张图的真实节点数: [3, 4, 5]


In [2]:
import torch
x = torch.randn(5,3)
print(x.shape)
print(x)

torch.Size([5, 3])
tensor([[-0.2719, -1.4537, -1.4641],
        [ 0.9816,  0.0939, -0.2177],
        [ 0.9343, -0.5926, -0.9244],
        [-0.2425,  1.0107,  0.3541],
        [-0.4509, -0.4991, -0.3357]])


In [4]:
import torch
A = torch.zeros(5,5)
edges = [(0,1),(0,2),(1,2),(2,3),(3,4)]
for u,v in edges:
    A[u,v] = 1
    A[v,u] = 1
print(A)
print(A.sum().item())

tensor([[0., 1., 1., 0., 0.],
        [1., 0., 1., 0., 0.],
        [1., 1., 0., 1., 0.],
        [0., 0., 1., 0., 1.],
        [0., 0., 0., 1., 0.]])
10.0


In [7]:
import torch
edges = [(0,1),(0,2),(1,2),(2,3),(3,4)]
directed_edges = edges + [(v,u) for u,v in edges]
edge_index = torch.tensor(directed_edges,dtype=torch.long).t()
print(edge_index.shape)
print(edge_index)

torch.Size([2, 10])
tensor([[0, 0, 1, 2, 3, 1, 2, 2, 3, 4],
        [1, 2, 2, 3, 4, 0, 0, 1, 2, 3]])


In [1]:
import torch
from torch_geometric.data import Data
X = torch.randn(5,3)
edge_index = torch.tensor([[0,1,0,2,1,2,2,3,3,4],
                          [1,0,2,0,2,1,3,2,4,3]],dtype=torch.long)
g = Data(x=X,edge_index=edge_index)
print(g.num_nodes)
print(g.num_edges)
print(g.has_self_loops())

d:\pythonprojects\practice-github\torch_final\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


5
10
False
