In [2]:
import numpy as np
import time
N = 10_000_000
py_list = list(range(N))
np_arr = np.arange(N)
t0 = time.perf_counter()
s = sum(x*x for x in py_list)
print("纯Python:",round(time.perf_counter()-t0,3))
t0 = time.perf_counter()
s = np.sum(np_arr ** 2)
print("NumPy:",round(time.perf_counter()-t0,3))

纯Python: 0.414
NumPy: 0.023


In [36]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
c = np.array([1,2.5,3])
d = np.array([(1,2),(3,4)],dtype=[('x','i4'),('y','f4')])
print(np.zeros((3,4)))
print(np.ones((2,3)))
print(np.full((2,2),3.14))
print(np.empty((2,2)))
print(np.zeros_like(b))
print(np.arange(0,10,2))
print(np.linspace(0,1,5))
print(np.logspace(0,2,5))
print(np.geomspace(1,1000,4))
print(np.eye(3))
print(np.eye(3,k=1))
print(np.diag([1,2,3]))
print(np.tri(3,4))
grid = np.fromfunction(lambda i,j:i*4+j,(3,4),dtype=int)
it = np.fromiter((x*x for x in range(5)),dtype=float,count=5)
rng = np.random.default_rng(42)
print(rng.random((2,3)))
print(rng.integers(0,10,size=5))
print(rng.normal(0,1,size=5))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[3.14 3.14]
 [3.14 3.14]]
[[3.14 3.14]
 [3.14 3.14]]
[[0. 0. 0.]
 [0. 0. 0.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[  1.           3.16227766  10.          31.6227766  100.        ]
[   1.   10.  100. 1000.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]]
[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]
[7 7 7 7 5]
[-0.85304393  0.87939797  0.77779194  0.0660307   1.12724121]


In [44]:
a = np.arange(24,dtype=np.int32).reshape(2,3,4)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.nbytes)
print(a.strides)
print(a.T.shape)
print(a.flags)

(2, 3, 4)
3
24
int32
4
96
(48, 16, 4)
(4, 3, 2)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [54]:
a = np.array([1,2,3],dtype=np.int8)
print(a.dtype.itemsize)
b = np.array([-56],dtype=np.int8)
print(b + np.array([100],dtype=np.int8))
x = np.array([0.1,0.2,0.3])
print(x.sum() == 0.6)
print(np.isclose(x.sum(),0.6))
print(np.allclose([1.0,2.0],[1.0+1e-9,2.0]))
print(np.array([1.9,2.1]).astype(int))
print(np.round([1.5,2.5,3.5]).astype(int))
print(np.array(["1","2","3"]).astype(float))
v = np.array([1.0,np.nan,3.0,np.inf])
print(np.isnan(v),np.isinf(v))
print(np.nan+5)

1
[44]
False
True
True
[1 2]
[2 2 4]
[1. 2. 3.]
[False  True False False] [False False False  True]
nan


In [70]:
a = np.arange(12).reshape(3,4)
print(a[0,1])
print(a[0])
print(a[0,1])
print(a[0:1,1:2])
print(a[::2])
print(a[:,::2])
print(a[::-1])
print(a[::-1,::-1])
print(a[[0,2]])
print(a[np.ix_([0,2],[1,3])])
mask = a > 5
print(mask)
print(a[mask])
print(a[a % 3 == 0])
a[a < 0] = 0
x = np.array([-3,-1,2,5])
print(np.where(x > 0, x, 0))
idx = np.where(x > 0 )[0]
print(np.where(x > 0))

1
[0 1 2 3]
1
[[1]]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]
[[ 0  1  2  3]
 [ 8  9 10 11]]
[[ 1  3]
 [ 9 11]]
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11]
[0 3 6 9]
[0 0 2 5]
(array([2, 3]),)


In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset,DataLoader,random_split
import numpy as np
from sklearn.metrics import accuracy_score,precision_score,recall_score
import matplotlib.pyplot as plt
BATCH_SIZE = 32
EPOCHS = 50
LEARNING_RATE = 0.001
INPUT_FEATURES = 10
NUM_CLASSES = 2
TRAIN_RATIO = 0.8
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device:{device}")
class RandomDataset(Dataset):
    def __init__(self,num_samples=1000,input_dim=10,num_classes=2):
        self.X = torch.randn(num_samples,input_dim)
        self.y = torch.randint(0,num_classes,(num_samples,))
    def __len__(self):
        return len(self.X)
    def __getitem__(self,idx):
        return self.X[idx],self.y[idx]
full_dataset = RandomDataset(num_samples=1000,input_dim=INPUT_FEATURES,num_classes=NUM_CLASSES)
train_size = int(TRAIN_RATIO * len(full_dataset))
val_size = len(full_dataset) - train_size
train_dataset,val_dataset = random_spslit(full_dataset,[train_size,val_size])
train_loader = DataLoader(train_dataset,batch_size=BATCH_SIZE,shuffle=True)
val_loader = DataLoader(val_dataset,batch_size=BATCH_SIZE,shuffle=False)
class SimpleNN(nn.Module):
    def __init__(self,input_dim,hidden_dim,num_classes):
        super(SimpleNN,self).__init__()
        self.fc1 = nn.Linear(input_dim,hidden_dim)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_dim,num_classes)
    def forward(self,x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out
model = SimpleNN(input_dim=INPUT_FEATURES,hidden_dim=32,num_classes=NUM_CLASSES).to(device)


Using device:cuda
