In [1]:
import numpy as np
from sklearn.impute import SimpleImputer
X = np.array([[1,2],[np.nan,3],[7,6],[4,np.nan]])
imputer = SimpleImputer(strategy='mean')
X_filled = imputer.fit_transform(X)
print(X_filled)

[[1.         2.        ]
 [4.         3.        ]
 [7.         6.        ]
 [4.         3.66666667]]


In [4]:
import numpy as np
from sklearn.impute import SimpleImputer
X = np.array([[1,10],[2,11],[3,12],[100,np.nan],[np.nan,13]])
print(X)
mean_imp = SimpleImputer(strategy='mean')
print("均值填充结果:\n",mean_imp.fit_transform(X))
median_imp = SimpleImputer(strategy='median')
print('中位数填充结果:\n',median_imp.fit_transform(X))

[[  1.  10.]
 [  2.  11.]
 [  3.  12.]
 [100.  nan]
 [ nan  13.]]
均值填充结果:
 [[  1.   10. ]
 [  2.   11. ]
 [  3.   12. ]
 [100.   11.5]
 [ 26.5  13. ]]
中位数填充结果:
 [[  1.   10. ]
 [  2.   11. ]
 [  3.   12. ]
 [100.   11.5]
 [  2.5  13. ]]


In [8]:
from sklearn.impute import KNNImputer
X = np.array([[1,2,np.nan],[3,4,5],[np.nan,6,7],[8,9,10]])
print(X)
knn_imp = KNNImputer(n_neighbors=2)
print(knn_imp.fit_transform(X))

[[ 1.  2. nan]
 [ 3.  4.  5.]
 [nan  6.  7.]
 [ 8.  9. 10.]]
[[ 1.   2.   6. ]
 [ 3.   4.   5. ]
 [ 5.5  6.   7. ]
 [ 8.   9.  10. ]]


In [10]:
from sklearn.preprocessing import StandardScaler
X = np.array([[1,100],[2,200],[3,300],[4,400]])
print(X)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("标准化后数据：\n", X_scaled)
print("每列均值：", X_scaled.mean(axis=0))  
print("每列标准差：", X_scaled.std(axis=0))


[[  1 100]
 [  2 200]
 [  3 300]
 [  4 400]]
标准化后数据：
 [[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]
每列均值： [0. 0.]
每列标准差： [1. 1.]


In [2]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
X = np.array([[10,200],[20,400],[30,600]])
print(X)
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled)
print(X_scaled.min(axis=0))
print(X_scaled.max(axis=0))

[[ 10 200]
 [ 20 400]
 [ 30 600]]
[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]
[0. 0.]
[1. 1.]


In [4]:
from sklearn.preprocessing import LabelEncoder
import numpy as np
y = ['low','medium','high','low','high']
le = LabelEncoder()
y_encoded = le.fit_transform(y)
print("编码结果:",y_encoded)
print("还原结果:",le.inverse_transform(y_encoded))
mapping = {'low':0,'medium':1,'high':2}
y_custom = [mapping[val] for val in y]
print("自定义编码:",y_custom)

编码结果: [1 2 0 1 0]
还原结果: ['low' 'medium' 'high' 'low' 'high']
自定义编码: [0, 1, 2, 0, 2]


In [6]:
from sklearn.preprocessing import OneHotEncoder
X_train = np.array([['red'],['green'],['blue']])
print(X_train)
X_test = np.array([['yellow'],['red']])
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoder.fit(X_train)
print('训练集编码:\n',encoder.transform(X_train))
print('测试集编码:\n',encoder.transform(X_test))

[['red']
 ['green']
 ['blue']]
训练集编码:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
测试集编码:
 [[0. 0. 0.]
 [0. 0. 1.]]


In [11]:
person = {
    "name": "小明",
    "age": 20,
    "city": "苏州",
    "is_student": True
}
print(person)
print(type(person))
print(len(person))
empty_dict = {}
empty_dict2 = dict()
print(type(empty_dict))

{'name': '小明', 'age': 20, 'city': '苏州', 'is_student': True}
<class 'dict'>
4
<class 'dict'>


In [17]:
person = {'name':'小明','age':20,'city':'苏州'}
print(person['name'])
print(person['age'])
print(person.get('name'))
print(person.get('job'))
print(person.get('job','未知'))
print(person.get('age',18))

小明
20
小明
None
未知
20


In [ ]:
person