In [23]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
b = np.arange(0,10,2)
print(b)
c = np.linspace(0.0,1.0,5)
print(c)
d = np.zeros((3,4))
print(d)
e = np.random.randn(3,4)
print(e)
x = np.array([1,2,3,4,5])
result_slow = [i ** 2 for i in x]
result_fast = x ** 2
print(result_fast)
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A@B)
print(A*B)
print(A.T)
print(np.linalg.det(A))

[1 2 3 4 5]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[-0.25053884 -0.63423304  0.97598871 -0.36638735]
 [-0.30399323  0.80793931  0.06257142  0.42756795]
 [-0.42569284 -0.28258168  0.53822136 -0.73232468]]
[ 1  4  9 16 25]
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
[[1 3]
 [2 4]]
-2.0000000000000004


In [ ]:
import numpy as np
a = np.array([1,2,3])
print(a+10)
col = np.array([[1],[2],[3]])
row = np.array([10,20,30])
print(col+row)
data = np.random.randn(100,5)
mean = data.mean(axis=0)
std = data.std(axis=0)
normalized = (data-mean)/std
print(normalized.mean(axis=0).round(6))
print(normalized.std(axis=0).round(6))

[11 12 13]
[[11 21 31]
 [12 22 32]
 [13 23 33]]
[ 0.  0. -0.  0.  0.]
[1. 1. 1. 1. 1.]


In [42]:
import pandas as pd
import numpy as np
data = {
    "user_id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "name": ["Alice", "Bob", "Charlie", "David", "Eve",
             "Frank", "Grace", "Helen", "Ivan", "Jack"],
    "age": [25, 30, np.nan, 35, 28, 42, np.nan, 31, 26, 38],
    "salary": [50000, 60000, 75000, np.nan, 55000, 80000, 65000, 70000, 48000, 90000],
    "department": ["Engineering", "Marketing", "Engineering", "Sales", "Marketing",
                   "Engineering", "Sales", "Engineering", "Marketing", "Sales"],
    "join_date": pd.to_datetime(["2020-01-15", "2019-06-20", "2021-03-10",
                                  "2018-11-05", "2022-02-28", "2017-08-12",
                                  "2020-07-01", "2019-12-15", "2023-01-20", "2016-04-30"]),
    "is_active": [True, True, False, True, True, False, True, True, False, True],
}
df = pd.DataFrame(data)
print("=== 数据概览 ===")
df.info()
print(df.shape)
print(df.head(3))
print(df.describe())

=== 数据概览 ===
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   user_id     10 non-null     int64         
 1   name        10 non-null     str           
 2   age         8 non-null      float64       
 3   salary      9 non-null      float64       
 4   department  10 non-null     str           
 5   join_date   10 non-null     datetime64[us]
 6   is_active   10 non-null     bool          
dtypes: bool(1), datetime64[us](1), float64(2), int64(1), str(2)
memory usage: 754.0 bytes
(10, 7)
   user_id     name   age   salary   department  join_date  is_active
0        1    Alice  25.0  50000.0  Engineering 2020-01-15       True
1        2      Bob  30.0  60000.0    Marketing 2019-06-20       True
2        3  Charlie   NaN  75000.0  Engineering 2021-03-10      False
        user_id        age        salary            join_date
count  10.00000   8.0000

In [59]:
import pandas as pd
import numpy as np
data = {
    "user_id": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "name": ["Alice", "Bob", "Charlie", "David", "Eve",
             "Frank", "Grace", "Helen", "Ivan", "Jack"],
    "age": [25, 30, np.nan, 35, 28, 42, np.nan, 31, 26, 38],
    "salary": [50000, 60000, 75000, np.nan, 55000, 80000, 65000, 70000, 48000, 90000],
    "department": ["Engineering", "Marketing", "Engineering", "Sales", "Marketing",
                   "Engineering", "Sales", "Engineering", "Marketing", "Sales"],
    "join_date": pd.to_datetime(["2020-01-15", "2019-06-20", "2021-03-10",
                                  "2018-11-05", "2022-02-28", "2017-08-12",
                                  "2020-07-01", "2019-12-15", "2023-01-20", "2016-04-30"]),
    "is_active": [True, True, False, True, True, False, True, True, False, True],
}
df = pd.DataFrame(data)
print("=== 缺失值统计 ===")
print(df.isnull().sum())
print(df.isnull().mean().round(2))
df_drop = df.dropna()
print(len(df_drop),len(df))
df['age_filled'] = df['age'].fillna(df['age'].mean())
df['salary_filled'] = df['salary'].fillna(df['salary'].median())
df['age_ffill'] = df['age'].ffill()
df['age_bfill'] = df['age'].bfill()
df['department'] = df['department'].fillna('Unkown')
print("\n=== 填充后 ===")
print(df[['age','age_filled','age_ffill','age_bfill']])
print(f"\n=== salary 填充 ===")
print(df['salary'].median())
print(df[['salary','salary_filled']])

=== 缺失值统计 ===
user_id       0
name          0
age           2
salary        1
department    0
join_date     0
is_active     0
dtype: int64
user_id       0.0
name          0.0
age           0.2
salary        0.1
department    0.0
join_date     0.0
is_active     0.0
dtype: float64
7 10

=== 填充后 ===
    age  age_filled  age_ffill  age_bfill
0  25.0      25.000       25.0       25.0
1  30.0      30.000       30.0       30.0
2   NaN      31.875       30.0       35.0
3  35.0      35.000       35.0       35.0
4  28.0      28.000       28.0       28.0
5  42.0      42.000       42.0       42.0
6   NaN      31.875       42.0       31.0
7  31.0      31.000       31.0       31.0
8  26.0      26.000       26.0       26.0
9  38.0      38.000       38.0       38.0

=== salary 填充 ===
65000.0
    salary  salary_filled
0  50000.0        50000.0
1  60000.0        60000.0
2  75000.0        75000.0
3      NaN        65000.0
4  55000.0        55000.0
5  80000.0        80000.0
6  65000.0        65000.0
7  70

In [67]:
import pandas as pd
import numpy as np
df['age'] = pd.to_numeric(df['age'],errors='coerce')
df['join_date'] = pd.to_datetime(df['join_date'])
df['department'] = df['department'].astype('category')
print(df['department'].dtype)
print(df['department'].cat.categories.tolist())
Q1 = df['salary'].quantile(0.25)
Q3 = df['salary'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
outliers = df[(df['salary']<lower)|(df['salary']>upper)]
print(lower,upper)
print(len(outliers))
df['salary_clipped'] = df['salary'].clip(lower=lower,upper=upper) 

category
['Engineering', 'Marketing', 'Sales']
25000.0 105000.0
0


In [72]:
import pandas as pd
import numpy as np
engineers = df[df['department']=='Engineering']
print(len(engineers))
senior_active = df[(df['age']>30)&(df['is_active']==True)]
print(len(senior_active))
name_contains_a = df[df['name'].str.contains('a',case=False)]
print(name_contains_a['name'].tolist())
df_sorted = df.sort_values('salary',ascending=False)
print(df_sorted[['name','salary']].to_string(index=False))
summary = df.groupby("department").agg(
    人数=("user_id", "count"),
    平均年龄=("age", "mean"),
    平均薪资=("salary", "mean"),
    活跃率=("is_active", "mean"),
).round(1)
print(summary)
pivot = pd.pivot_table(
    df,
    values='salary',
    index='department',
    columns='is_active',
    aggfunc='mean',
).round(0)
print(pivot)

4
3
['Alice', 'Charlie', 'David', 'Frank', 'Grace', 'Ivan', 'Jack']
   name  salary
   Jack 90000.0
  Frank 80000.0
Charlie 75000.0
  Helen 70000.0
  Grace 65000.0
    Bob 60000.0
    Eve 55000.0
  Alice 50000.0
   Ivan 48000.0
  David     NaN
             人数  平均年龄     平均薪资  活跃率
department                         
Engineering   4  32.7  68750.0  0.5
Marketing     3  28.0  54333.3  0.7
Sales         3  36.5  77500.0  1.0
is_active      False    True 
department                   
Engineering  77500.0  60000.0
Marketing    48000.0  57500.0
Sales            NaN  77500.0
